### ISSUE TITLE
Plugins page needs help!

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/janus-idp.io#1]
Overview:
The plugins page is a card view of all of our Janus plugins.

What's the problem:

1. Each "card" should have a hover state to change the background color of the card rather than underlining the text
2. Each "card" should have it's own logo as defined [here](https://github.com/janus-idp/janus-idp.io/blob/main/src/components/PluginsFeatures/index.js) but for some reason the same logo is displayed for most

Current screenshot:
<img width="1432" alt="Screenshot 2023-05-08 at 9 28 26 PM" src="https://user-images.githubusercontent.com/12504403/236971174-ce057c15-ed66-427a-9519-67b367804fda.png">

**Comment by serenamarie125** [comment]
@schultzp2020 is this something you could help with?

**Comment by schultzp2020** [comment]
@serenamarie125 ignore the colors for now; however, what do you think of the hover effect?

![hover](https://github.com/janus-idp/janus-idp.io/assets/52387464/fe04ac54-2c61-41e6-8d19-25a91722c347)

**Comment by serenamarie125** [comment]
This looks cool!  any chance you could use #F2F9F9  for the card color? we are using the Teal color Palette from PF:
https://www.patternfly.org/v4/guidelines/colors/
